### ISSUE TITLE
Not the same result depending on systems

### ISSUE THREAD

**Issue by RomainBlindy** [Endogen/TradeOgrePy#2]
***Config 1

OS: Windows 10
Programming Language version: Python 3.7.2
Method: fetchAccounts

***Config 2
OS: Raspbian 4.14
Programming Language version: Python 3.5.3

Hello,

Thanks for your wrapper. 
I have an issue/question about some weird thing. 
I have a code which works well on Config1 but does not restult exactly the same result on Config2.

`Result = Connect.order_book(Pair)
 print (Result)`

On Config1 i have a result well sorted by price, whereas on Config2 i have a result with datas unsorted by price (randomly positionned it seems).

Do you have an idea where it can come from ?

Thanks a lot,

Romain

**Comment by Endogen** [comment]
Hi

that is because of the Python version you are using. In Python 3.7 dictionaries are sorted by key per default. In Python 3.5 they are not sorted. If you want to sort the dictionary, read more about the `sorted()` function [here](https://www.pythoncentral.io/how-to-sort-python-dictionaries-by-key-or-value)

See [this](https://www.blog.pythonlibrary.org/2018/02/27/python-3-7-dictionaries-now-ordered) source

**Comment by RomainBlindy** [comment]
Thanks a lot for the reply this makes sense.
